# Generated by Django 4.1.5 on 2023-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_password_member_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='아이디'),
        ),
    ]
