# Generated by Django 4.1.5 on 2023-01-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '상품 댓글', 'verbose_name_plural': '상품 댓글'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='shinhan_product_comment',
        ),
    ]
